import { algorithm } from '../../config.json'
import { RandomCouponGenerator } from '../RandomCouponGenerator';
import { SequenceCouponGenerator } from '../SequenceCouponGenerator';

export namespace Utils {
    /**
    * Choose an specific generator
    * @returns An specific generator depending of the config file
    */
    export function chooseGenerator() {
        switch (algorithm) {
            case "sequence":
                return new SequenceCouponGenerator();
            case "random":
                return new RandomCouponGenerator();
            default:
                // Sequence is generated by default unless the algorithm property is changed to random
                return new SequenceCouponGenerator();
        }
    }
}
